---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: redisserver
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  playbook: playbooks/default.yml


verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    verifier:
      inspec_tests:
        - ../../redis_test
    attributes:
