---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  puppet_apt_repo: http://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
  require_chef_for_busser: false
  manifests_path: manifests
  modules_path: modules

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    provisioner:
      manifest: site.pp
    verifier:
      inspec_tests:
        - ../../redis_test
    attributes:
